# Generated by Django 6.0.3 on 2026-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_bitacoraentry_incident_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Racha Actual (Días)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última Conexión'),
        ),
    ]
